2025-08-24 10:30:48,439 - INFO - --- Starting On-Demand Log Processor ---
2025-08-24 10:30:48,440 - INFO - Found 2 new log file(s): SESSION_LOG_2025-08-24_10-30-25.json, SESSION_LOG_2025-08-24_10-30-31.json
2025-08-24 10:30:48,440 - INFO - 
--- Processing: SESSION_LOG_2025-08-24_10-30-25.json ---
2025-08-24 10:30:48,440 - INFO - Running calculation for SESSION_LOG_2025-08-24_10-30-25.json...
2025-08-24 10:30:48,529 - INFO - Error running calculation program: Command '['python', '-u', 'C:\\Users\\Charging\\CHARGING\\LOCAL_TO_CLOUD\\calculate_bill.py', 'C:\\Users\\Charging\\CHARGING\\ChargeSOM_LOGS\\Session_Logs\\SESSION_LOG_2025-08-24_10-30-25.json']' returned non-zero exit status 1.
2025-08-24 10:30:48,531 - INFO - Uploading SESSION_LOG_2025-08-24_10-30-25.json to configured repository...
2025-08-24 10:30:49,153 - INFO -  - Upload successful.
2025-08-24 10:30:50,519 - INFO -  - Successfully processed and logged SESSION_LOG_2025-08-24_10-30-25.json.
2025-08-24 10:30:50,519 - INFO - 
--- Processing: SESSION_LOG_2025-08-24_10-30-31.json ---
2025-08-24 10:30:50,519 - INFO - Running calculation for SESSION_LOG_2025-08-24_10-30-31.json...
2025-08-24 10:30:50,595 - INFO - Error running calculation program: Command '['python', '-u', 'C:\\Users\\Charging\\CHARGING\\LOCAL_TO_CLOUD\\calculate_bill.py', 'C:\\Users\\Charging\\CHARGING\\ChargeSOM_LOGS\\Session_Logs\\SESSION_LOG_2025-08-24_10-30-31.json']' returned non-zero exit status 1.
2025-08-24 10:30:50,595 - INFO - Uploading SESSION_LOG_2025-08-24_10-30-31.json to configured repository...
